//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------

namespace A2_B1
{
    public partial class _Default
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.TextBox txtStudentID;

        protected global::System.Web.UI.WebControls.TextBox txtNumber;

        protected global::System.Web.UI.WebControls.Button btnSubmit;

        protected global::System.Web.UI.WebControls.Label lblGrade;

        protected global::System.Web.UI.WebControls.Label lblAPlus;

        protected global::System.Web.UI.WebControls.Label lblBPlus;

        protected global::System.Web.UI.WebControls.Label lblCPlus;

        protected global::System.Web.UI.WebControls.Label lblF;
    }
}